Update Auth Options
wazuh/wazuh-puppet pull request #427
Opened 2021-11-17 17:47 UTC by vcerenu

# QA Standard pull request template

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

---

## Closing/Related Issues
Closes #386 

## Test plan (required)
- [x] I have tested the pipeline on Jenkins. (Mandatory)
https://ci.wazuh.info/view/Tests/job/Test_service/3273/
https://ci.wazuh.info/view/Tests/job/Test_service/3278

## Target Jenkins
- [x] Production
- [x] Staging

Are there dependencies with other repositories? (Remove unmark checks)
- [x] No

Are there dependencies with other pipelines? (Remove unmark checks)
- [x] No

## Description/Notes
Hello team,

This PR update the last parameters introduced in 4.3.0 auth section inside ossec.conf.

2021-11-17 18:17 UTC, lastranikos approved these changes
LGTM

2021-11-18 09:19 UTC, okynos requested changes
Minor change.

2021-11-18 09:19 UTC, okynos commented on manifests/params_manager.pp
> +      $ossec_auth_force_after_reg_time                 = '5s'
Set it to `1h`

2021-11-18 11:52 UTC, vcerenu commented on manifests/params_manager.pp
> +      $ossec_auth_force_after_reg_time                 = '5s'
Done

2021-11-18 11:53 UTC, okynos approved these changes
LGTM.

2021-11-18 11:54 UTC, merged