Added `yumreo_enabled` parameter
wazuh/wazuh-puppet pull request #488
Opened 2022-05-01 10:19 UTC by Tamerz

We want to have the YUM repo available, but we don't want it enabled by default. This is so a simple yum update doesn't upgrade our Wazuh agent since we pin ours to a specific version.

To do this, I added a `yumrepo_enabled` parameter to the `wazuh::agent` and `wazuh::manager` classes.

It will default to true to not break any current people's configuration.

This replaces the previous pull request I put in which I will close: https://github.com/wazuh/wazuh-puppet/pull/479

2022-09-18 07:26 UTC, Tamerz commented
Hello. Can someone please take a look at this when they have a chance?

2022-10-27 19:12 UTC, c-bordon requested changes
I was testing the proposed changes and I ran into problems deploying the manager and agent on Debian and Ubuntu systems, so I ask you if you can review the code and add a validation so that this parameter is not included in these systems.

2022-10-27 19:12 UTC, c-bordon commented on manifests/manager.pp
> +    install_options => [ { '--enablerepo'  => 'wazuh' }, ],
This parameter breaks the installation for Debian or Ubuntu systems:

E: The command line option --enablerepo=wazuh is not understood in combination with the other options

We need that this parameter is not added to these systems

2022-10-27 19:12 UTC, c-bordon commented on manifests/agent.pp
> +        install_options => [{ '--enablerepo'  => 'wazuh' }],
This parameter breaks the installation for Debian or Ubuntu systems:

E: The command line option --enablerepo=wazuh is not understood in combination with the other options

We need that this parameter is not added to these systems

2022-10-30 10:28 UTC, Tamerz commented
Honestly, without working unit tests, it is extremely difficult to contribute to this module. I'm going to close this pull request.

2022-10-30 10:28 UTC, closed without merging