Add Amazon Linux 2023 VDT default configuration
wazuh/wazuh-puppet pull request #762
Opened 2023-09-07 03:20 UTC by Leoquicenoz

|Related issue|
|---|
|wazuh/wazuh#17617|

## Description

This PR adds the corresponding Amazon Linux 2023 entry in the vulnerability detector default configuration after the changes in [Add support for Amazon Linux 2023 in Vulnerability Detector](https://github.com/wazuh/wazuh/issues/17617)

## DoD

- [x] Search for all the places where the vulnerability detector configuration block is defined and add the new Amazon Linux 2023 provider

2023-09-07 13:09 UTC, mateocervilla requested changes

2023-09-07 13:09 UTC, mateocervilla commented on manifests/params_manager.pp
> +      'amazon-linux-2023'
```suggestion
        'amazon-linux-2', 
        'amazon-linux-2023'
```

2023-09-18 17:41 UTC, MarcelKemp approved these changes

2023-09-21 14:03 UTC, teddytpc1 approved these changes

2023-09-21 14:45 UTC, mateocervilla approved these changes
LGTM!

2023-09-21 16:01 UTC, merged